#!/usr/bin/env ruby
# frozen_string_literal: true

require 'yaml'

file = ARGV[0]
data = YAML.load_file(file)

# Lists of pronouns whose conjungations are the same.
pronoun_groups = [
  %w[él ella usted],
  %w[nosotros nosotras],
  %w[vosotros vosotras],
  %w[ellos ellas ustedes]
]

# To output YAML with keys in the right order, we need to create new Hash
# objects and inser the value in the order we want the keys to appear.
pronoun_order = %w[yo tú vos él ella usted nosotros nosotras vosotros vosotras ellos ellas ustedes]

%w[indicativo subjuntivo imperativo].each do |mood|
  data[mood].each do |key, value|
    # Copy conjunctions for any missing pronouns.
    pronoun_groups.each do |group|
      present = []
      missing = []
      group.each do |pronoun|
        if value.include? pronoun
          present << pronoun
        else
          missing << pronoun
        end
      end
      next if present.empty? || missing.empty?

      missing.each do |fill|
        value[fill] = value[present[0]]
      end
    end

    # Create a new Hash with values inserted in the right key order.
    old_object = data[mood][key]
    new_object = {}
    keys = old_object.keys.sort_by { |p| pronoun_order.find_index(p) }
    keys.each { |k| new_object[k] = old_object[k] }
    # Replace the old Hash with the new complete and sorted one.
    data[mood][key] = new_object
  end
end

File.write(file, YAML.dump(data))
