#!/usr/bin/env ruby
# frozen_string_literal: true
# rubocop:disable Style/GlobalVars

require 'yaml'

file = ARGV[0]
$data = YAML.load_file(file)

puts format('Infinitivo: %s', $data['infinitivo'])
puts format('Gerundio: %s', $data['infinitivo'])
puts format('Participios: %s', $data['participio'].values.join(', '))

$pronouns = %w[yo tú vos él ella usted nosotros nosotras vosotros vosotras ellos ellas ustedes]

def print_tense(mood, tense)
  forms = $data[mood][tense]
  print '| '
  print tense.split.map(&:capitalize).join(' ')
  print ' |'
  $pronouns.each do |p|
    print ' '
    form = forms[p]
    if form.is_a?(Array)
      print form.join(', ')
    else
      print form
    end
    print ' |'
  end
  puts
end

def print_mood(mood)
  puts
  puts mood.capitalize
  print '| Tense |'
  $pronouns.each do |p|
    print ' '
    print p.capitalize
    print ' |'
  end
  puts

  print '|-' * ($pronouns.size + 1)
  puts '|'

  $data[mood].each_key do |tense|
    print_tense(mood, tense)
  end
end

%w[indicativo subjuntivo imperativo].each { |t| print_mood(t) }
